version: 1.0.0.{build}
image: Visual Studio 2022

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
    - ps: dotnet --info
    - ps: dotnet restore src

build_script:
    - ps: dotnet pack -c Release src

after_build:
- ps: >-
    $zipSettings = @{
        Path = Get-ChildItem -Path ".\src\bin\Release\*" -Exclude "*.nupkg"
        DestinationPath = "Flow.Plugin.RegJump.zip"
    }

    Compress-Archive @zipSettings

artifacts:
    - path: 'Flow.Plugin.RegJump.zip'